on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This is a demo'
      - run: echo 'We would build code here'
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This is a demo'
      - run: echo 'We would run tests here'
